In [14]:
import pandas as pd

pd.read_csv("results.csv")[10:50]

,ln,col,block,token,type
10,3,35,1,[,delimiter
11,3,36,1,],delimiter
12,3,38,1,args,identifier
13,3,42,1,),delimiter
14,3,44,2,{,delimiter
15,4,9,2,// Comment: this is a comment which will be ig...,comment
16,6,9,2,// Keywords,comment
17,7,9,2,int,keyword
18,7,13,2,count,identifier
19,7,19,2,=,operation
20,7,21,2,0,literal
21,7,22,2,;,delimiter
22,8,9,2,for,keyword
23,8,13,2,(,delimiter
24,8,14,2,int,keyword
25,8,14,2,i,identifier
26,8,20,2,=,operation
27,8,22,2,0,literal
28,8,23,2,;,delimiter
29,8,14,2,i,identifier
30,8,27,2,<,operation
31,8,29,2,5,literal
32,8,23,2,;,delimiter
33,8,14,2,i,identifier
34,8,33,2,+,operation
35,8,33,2,+,operation
36,8,35,2,),delimiter
37,8,37,3,{,delimiter
38,9,13,3,count,identifier
39,9,19,3,+,operation
40,9,20,3,=,operation
41,9,22,3,i,identifier
42,9,23,3,;,delimiter
43,10,9,2,},delimiter
44,12,9,2,// Identifiers,comment
45,13,9,2,String,keyword
46,13,16,2,variableName,identifier
47,13,29,2,=,operation
48,13,31,2,"""example""",string_literal
49,13,40,2,;,delimiter